import { mockProfile } from '../type/interface';

export const mockProfilesData: mockProfile[] = [
  {
    id: '1',
    accountId: '1',
    country: 'Country_1',
    marketplace: 'Marketplace_1',
  },
  {
    id: '2',
    accountId: '1',
    country: 'Country_2',
    marketplace: 'Marketplace_2',
  },
  {
    id: '3',
    accountId: '1',
    country: 'Country_3',
    marketplace: 'Marketplace_3',
  },
  {
    id: '1',
    accountId: '2',
    country: 'Country_1',
    marketplace: 'Marketplace_1',
  },
  {
    id: '1',
    accountId: '3',
    country: 'Country_1',
    marketplace: 'Marketplace_1',
  },
  {
    id: '2',
    accountId: '3',
    country: 'Country_2',
    marketplace: 'Marketplace_2',
  },
  {
    id: '3',
    accountId: '3',
    country: 'Country_3',
    marketplace: 'Marketplace_3',
  },
  {
    id: '4',
    accountId: '3',
    country: 'Country_4',
    marketplace: 'Marketplace_4',
  },
  {
    id: '5',
    accountId: '3',
    country: 'Country_5',
    marketplace: 'Marketplace_5',
  },
  {
    id: '1',
    accountId: '4',
    country: 'Country_1',
    marketplace: 'Marketplace_1',
  },
  {
    id: '1',
    accountId: '5',
    country: 'Country_1',
    marketplace: 'Marketplace_1',
  },
  {
    id: '2',
    accountId: '5',
    country: 'Country_2',
    marketplace: 'Marketplace_2',
  },
  {
    id: '3',
    accountId: '5',
    country: 'Country_3',
    marketplace: 'Marketplace_3',
  },
  {
    id: '4',
    accountId: '5',
    country: 'Country_4',
    marketplace: 'Marketplace_4',
  },
  {
    id: '1',
    accountId: '6',
    country: 'Country_1',
    marketplace: 'Marketplace_1',
  },
  {
    id: '2',
    accountId: '6',
    country: 'Country_2',
    marketplace: 'Marketplace_2',
  },
  {
    id: '3',
    accountId: '6',
    country: 'Country_3',
    marketplace: 'Marketplace_3',
  },
  {
    id: '4',
    accountId: '6',
    country: 'Country_4',
    marketplace: 'Marketplace_4',
  },
  {
    id: '1',
    accountId: '7',
    country: 'Country_1',
    marketplace: 'Marketplace_1',
  },
  {
    id: '1',
    accountId: '8',
    country: 'Country_1',
    marketplace: 'Marketplace_1',
  },
  {
    id: '2',
    accountId: '8',
    country: 'Country_2',
    marketplace: 'Marketplace_2',
  },
  {
    id: '3',
    accountId: '8',
    country: 'Country_3',
    marketplace: 'Marketplace_3',
  },
  {
    id: '1',
    accountId: '9',
    country: 'Country_1',
    marketplace: 'Marketplace_1',
  },
  {
    id: '1',
    accountId: '11',
    country: 'Country_1',
    marketplace: 'Marketplace_1',
  },
  {
    id: '2',
    accountId: '11',
    country: 'Country_2',
    marketplace: 'Marketplace_2',
  },
  {
    id: '3',
    accountId: '11',
    country: 'Country_3',
    marketplace: 'Marketplace_3',
  },
  {
    id: '1',
    accountId: '12',
    country: 'Country_1',
    marketplace: 'Marketplace_1',
  },
  {
    id: '2',
    accountId: '12',
    country: 'Country_2',
    marketplace: 'Marketplace_2',
  },
  {
    id: '3',
    accountId: '12',
    country: 'Country_3',
    marketplace: 'Marketplace_3',
  },
  {
    id: '4',
    accountId: '12',
    country: 'Country_4',
    marketplace: 'Marketplace_4',
  },
  {
    id: '1',
    accountId: '13',
    country: 'Country_1',
    marketplace: 'Marketplace_1',
  },
  {
    id: '2',
    accountId: '13',
    country: 'Country_2',
    marketplace: 'Marketplace_2',
  },
  {
    id: '3',
    accountId: '13',
    country: 'Country_3',
    marketplace: 'Marketplace_3',
  },
  {
    id: '4',
    accountId: '13',
    country: 'Country_4',
    marketplace: 'Marketplace_4',
  },
  {
    id: '1',
    accountId: '14',
    country: 'Country_1',
    marketplace: 'Marketplace_1',
  },
  {
    id: '2',
    accountId: '14',
    country: 'Country_2',
    marketplace: 'Marketplace_2',
  },
  {
    id: '3',
    accountId: '14',
    country: 'Country_3',
    marketplace: 'Marketplace_3',
  },
  {
    id: '4',
    accountId: '14',
    country: 'Country_4',
    marketplace: 'Marketplace_4',
  },
  {
    id: '1',
    accountId: '15',
    country: 'Country_1',
    marketplace: 'Marketplace_1',
  },
  {
    id: '2',
    accountId: '15',
    country: 'Country_2',
    marketplace: 'Marketplace_2',
  },
  {
    id: '3',
    accountId: '15',
    country: 'Country_3',
    marketplace: 'Marketplace_3',
  },
  {
    id: '4',
    accountId: '15',
    country: 'Country_4',
    marketplace: 'Marketplace_4',
  },
  {
    id: '5',
    accountId: '15',
    country: 'Country_5',
    marketplace: 'Marketplace_5',
  },
  {
    id: '1',
    accountId: '16',
    country: 'Country_1',
    marketplace: 'Marketplace_1',
  },
  {
    id: '2',
    accountId: '16',
    country: 'Country_2',
    marketplace: 'Marketplace_2',
  },
  {
    id: '3',
    accountId: '16',
    country: 'Country_3',
    marketplace: 'Marketplace_3',
  },
  {
    id: '4',
    accountId: '16',
    country: 'Country_4',
    marketplace: 'Marketplace_4',
  },
  {
    id: '5',
    accountId: '16',
    country: 'Country_5',
    marketplace: 'Marketplace_5',
  },
  {
    id: '1',
    accountId: '17',
    country: 'Country_1',
    marketplace: 'Marketplace_1',
  },
  {
    id: '2',
    accountId: '17',
    country: 'Country_2',
    marketplace: 'Marketplace_2',
  },
  {
    id: '3',
    accountId: '17',
    country: 'Country_3',
    marketplace: 'Marketplace_3',
  },
  {
    id: '4',
    accountId: '17',
    country: 'Country_4',
    marketplace: 'Marketplace_4',
  },
  {
    id: '5',
    accountId: '17',
    country: 'Country_5',
    marketplace: 'Marketplace_5',
  },
  {
    id: '1',
    accountId: '18',
    country: 'Country_1',
    marketplace: 'Marketplace_1',
  },
  {
    id: '1',
    accountId: '19',
    country: 'Country_1',
    marketplace: 'Marketplace_1',
  },
  {
    id: '2',
    accountId: '19',
    country: 'Country_2',
    marketplace: 'Marketplace_2',
  },
  {
    id: '3',
    accountId: '19',
    country: 'Country_3',
    marketplace: 'Marketplace_3',
  },
  {
    id: '4',
    accountId: '19',
    country: 'Country_4',
    marketplace: 'Marketplace_4',
  },
  {
    id: '5',
    accountId: '19',
    country: 'Country_5',
    marketplace: 'Marketplace_5',
  },
  {
    id: '1',
    accountId: '20',
    country: 'Country_1',
    marketplace: 'Marketplace_1',
  },
  {
    id: '2',
    accountId: '20',
    country: 'Country_2',
    marketplace: 'Marketplace_2',
  },
  {
    id: '3',
    accountId: '20',
    country: 'Country_3',
    marketplace: 'Marketplace_3',
  },
  {
    id: '4',
    accountId: '20',
    country: 'Country_4',
    marketplace: 'Marketplace_4',
  },
  {
    id: '5',
    accountId: '20',
    country: 'Country_5',
    marketplace: 'Marketplace_5',
  },
  {
    id: '1',
    accountId: '21',
    country: 'Country_1',
    marketplace: 'Marketplace_1',
  },
  {
    id: '1',
    accountId: '22',
    country: 'Country_1',
    marketplace: 'Marketplace_1',
  },
  {
    id: '2',
    accountId: '22',
    country: 'Country_2',
    marketplace: 'Marketplace_2',
  },
  {
    id: '3',
    accountId: '22',
    country: 'Country_3',
    marketplace: 'Marketplace_3',
  },
  {
    id: '4',
    accountId: '22',
    country: 'Country_4',
    marketplace: 'Marketplace_4',
  },
  {
    id: '1',
    accountId: '23',
    country: 'Country_1',
    marketplace: 'Marketplace_1',
  },
  {
    id: '2',
    accountId: '23',
    country: 'Country_2',
    marketplace: 'Marketplace_2',
  },
  {
    id: '1',
    accountId: '24',
    country: 'Country_1',
    marketplace: 'Marketplace_1',
  },
  {
    id: '2',
    accountId: '24',
    country: 'Country_2',
    marketplace: 'Marketplace_2',
  },
  {
    id: '1',
    accountId: '25',
    country: 'Country_1',
    marketplace: 'Marketplace_1',
  },
  {
    id: '2',
    accountId: '25',
    country: 'Country_2',
    marketplace: 'Marketplace_2',
  },
  {
    id: '1',
    accountId: '26',
    country: 'Country_1',
    marketplace: 'Marketplace_1',
  },
  {
    id: '2',
    accountId: '26',
    country: 'Country_2',
    marketplace: 'Marketplace_2',
  },
  {
    id: '3',
    accountId: '26',
    country: 'Country_3',
    marketplace: 'Marketplace_3',
  },
  {
    id: '4',
    accountId: '26',
    country: 'Country_4',
    marketplace: 'Marketplace_4',
  },
  {
    id: '1',
    accountId: '27',
    country: 'Country_1',
    marketplace: 'Marketplace_1',
  },
  {
    id: '2',
    accountId: '27',
    country: 'Country_2',
    marketplace: 'Marketplace_2',
  },
  {
    id: '1',
    accountId: '28',
    country: 'Country_1',
    marketplace: 'Marketplace_1',
  },
  {
    id: '2',
    accountId: '28',
    country: 'Country_2',
    marketplace: 'Marketplace_2',
  },
  {
    id: '3',
    accountId: '28',
    country: 'Country_3',
    marketplace: 'Marketplace_3',
  },
  {
    id: '4',
    accountId: '28',
    country: 'Country_4',
    marketplace: 'Marketplace_4',
  },
  {
    id: '1',
    accountId: '29',
    country: 'Country_1',
    marketplace: 'Marketplace_1',
  },
  {
    id: '2',
    accountId: '29',
    country: 'Country_2',
    marketplace: 'Marketplace_2',
  },
  {
    id: '3',
    accountId: '29',
    country: 'Country_3',
    marketplace: 'Marketplace_3',
  },
  {
    id: '1',
    accountId: '30',
    country: 'Country_1',
    marketplace: 'Marketplace_1',
  },
  {
    id: '2',
    accountId: '30',
    country: 'Country_2',
    marketplace: 'Marketplace_2',
  },
  {
    id: '3',
    accountId: '30',
    country: 'Country_3',
    marketplace: 'Marketplace_3',
  },
  {
    id: '4',
    accountId: '30',
    country: 'Country_4',
    marketplace: 'Marketplace_4',
  },
  {
    id: '1',
    accountId: '31',
    country: 'Country_1',
    marketplace: 'Marketplace_1',
  },
  {
    id: '2',
    accountId: '31',
    country: 'Country_2',
    marketplace: 'Marketplace_2',
  },
  {
    id: '3',
    accountId: '31',
    country: 'Country_3',
    marketplace: 'Marketplace_3',
  },
  {
    id: '4',
    accountId: '31',
    country: 'Country_4',
    marketplace: 'Marketplace_4',
  },
  {
    id: '5',
    accountId: '31',
    country: 'Country_5',
    marketplace: 'Marketplace_5',
  },
  {
    id: '1',
    accountId: '32',
    country: 'Country_1',
    marketplace: 'Marketplace_1',
  },
  {
    id: '2',
    accountId: '32',
    country: 'Country_2',
    marketplace: 'Marketplace_2',
  },
  {
    id: '3',
    accountId: '32',
    country: 'Country_3',
    marketplace: 'Marketplace_3',
  },
  {
    id: '4',
    accountId: '32',
    country: 'Country_4',
    marketplace: 'Marketplace_4',
  },
  {
    id: '5',
    accountId: '32',
    country: 'Country_5',
    marketplace: 'Marketplace_5',
  },
  {
    id: '1',
    accountId: '33',
    country: 'Country_1',
    marketplace: 'Marketplace_1',
  },
  {
    id: '1',
    accountId: '34',
    country: 'Country_1',
    marketplace: 'Marketplace_1',
  },
  {
    id: '2',
    accountId: '34',
    country: 'Country_2',
    marketplace: 'Marketplace_2',
  },
  {
    id: '3',
    accountId: '34',
    country: 'Country_3',
    marketplace: 'Marketplace_3',
  },
  {
    id: '1',
    accountId: '35',
    country: 'Country_1',
    marketplace: 'Marketplace_1',
  },
  {
    id: '1',
    accountId: '36',
    country: 'Country_1',
    marketplace: 'Marketplace_1',
  },
  {
    id: '2',
    accountId: '36',
    country: 'Country_2',
    marketplace: 'Marketplace_2',
  },
  {
    id: '3',
    accountId: '36',
    country: 'Country_3',
    marketplace: 'Marketplace_3',
  },
  {
    id: '4',
    accountId: '36',
    country: 'Country_4',
    marketplace: 'Marketplace_4',
  },
  {
    id: '5',
    accountId: '36',
    country: 'Country_5',
    marketplace: 'Marketplace_5',
  },
  {
    id: '1',
    accountId: '37',
    country: 'Country_1',
    marketplace: 'Marketplace_1',
  },
  {
    id: '2',
    accountId: '37',
    country: 'Country_2',
    marketplace: 'Marketplace_2',
  },
  {
    id: '1',
    accountId: '38',
    country: 'Country_1',
    marketplace: 'Marketplace_1',
  },
  {
    id: '2',
    accountId: '38',
    country: 'Country_2',
    marketplace: 'Marketplace_2',
  },
  {
    id: '3',
    accountId: '38',
    country: 'Country_3',
    marketplace: 'Marketplace_3',
  },
  {
    id: '1',
    accountId: '39',
    country: 'Country_1',
    marketplace: 'Marketplace_1',
  },
  {
    id: '2',
    accountId: '39',
    country: 'Country_2',
    marketplace: 'Marketplace_2',
  },
  {
    id: '3',
    accountId: '39',
    country: 'Country_3',
    marketplace: 'Marketplace_3',
  },
  {
    id: '4',
    accountId: '39',
    country: 'Country_4',
    marketplace: 'Marketplace_4',
  },
  {
    id: '5',
    accountId: '39',
    country: 'Country_5',
    marketplace: 'Marketplace_5',
  },
  {
    id: '1',
    accountId: '40',
    country: 'Country_1',
    marketplace: 'Marketplace_1',
  },
  {
    id: '2',
    accountId: '40',
    country: 'Country_2',
    marketplace: 'Marketplace_2',
  },
  {
    id: '3',
    accountId: '40',
    country: 'Country_3',
    marketplace: 'Marketplace_3',
  },
  {
    id: '4',
    accountId: '40',
    country: 'Country_4',
    marketplace: 'Marketplace_4',
  },
  {
    id: '5',
    accountId: '40',
    country: 'Country_5',
    marketplace: 'Marketplace_5',
  },
];
